themes/proton-carbon/v1/theme.json
Enhanced the text selection highlighting for the proton-carbon theme, making it easier to identify what you have selected.
=> Improve text selection in proton-carbon

themes/midnight/v1/theme.json
Created midnight/v1/theme.json to add the midnight theme to Notesnoook
=> Add the midnight theme to Notesnook

themes/midnight/v1/theme.json
Fix the navigation menu hover background and selected background colors to behave as expected in the Midnight theme.
=> Midnight: Fix navigation menu hover background

themes/midnight/v1/theme.json
Update midnight to 1.3 to fix various accents on mobile devices.
=> Update midnight to 1.3

themes/sweetpink/v1/theme.json
Minor changes under sheet section for Mobile
=> update sweetpink theme to 1.1

themes/cloud/v1/theme.json
Minor changes for 2.6.2 update
=> update cloud theme to 1.4

themes/sweetpink/v1/theme.json
Minor changes for 2.6.2 update
=> update sweetpink theme to 1.2

themes/midnight/v1/theme.json
Update the midnight theme to account for the changes introduced in Notesnook 2.6.2
=> Update midnight for 2.6.2 release

themes/midnight/v1/theme.json
Fix accent colors, mostly seen in mobile but some on desktop
=> Fix accents in Midnight

themes/cloud/v1/theme.json
=> update cloud theme to 1.5

themes/proton-snow/v1/theme.json
Minor changes based on the theme engine update
=> update proton-snow theme

themes/proton-monokai/v1/theme.json, themes/proton-snow/v1/theme.json
Minor changes based on the theme engine update
=> update proton-monokai theme

themes/light-orange/v1/theme.json, themes/light-red/v1/theme.json
Created Light Orange and Light Red Themes.
=> Add light-orange and light-red themes

themes/proton-carbon/v1/theme.json, themes/proton-monokai/v1/theme.json
Used darker color for text selection in editor
=> update proton-carbon theme

themes/dark-and-light/v1/theme.json, themes/light-and-dark/v1/theme.json, themes/limitless/v1/theme.json, themes/milky-way/v1/theme.json
This is a dark theme without any separators to make it more immersive for new PWA top bar.
=> Add Limitless theme.

themes/midnight/v1/theme.json
Fixed color of selected items in editor toolbar
=> Update "midnight" theme.json

themes/forevernote-dark/v1/theme.json
=> Update forevernote-dark theme

themes/fouces-fox/v1/theme.json, themes/slate-stone/v1/theme.json
themes with a soft visual and reduced glare.
=> add slate-stone theme & add fouces-fox theme

themes/nanab-berry/v1/theme.json
Side-by-Side Comparison:
| Before | After |
|---|---|
| <img src="https://github.com/user-attachments/assets/280559f2-314d-4c5b-89b8-ab3dde330539" alt="Before Image"> | <img src="https://github.com/user-attachments/assets/d493fc20-923f-4ffa-a4be-cb020e767c30" alt="After Image"> |
=> [Nanab Berry Theme] Enhanced color palette for a more enjoyable interface

themes/everforest-dark/v1/theme.json
Adjusted list view color palette for improved visual harmony
=> Updated Everforest Dark Theme

themes/mystic-dawn/v1/theme.json
Updated note list colors to provide better contrast when a note is selected, improving overall note distinguishability.
=>  Improve note list contrast for selected notes

themes/nanab-berry/v1/theme.json
Improved note list contrast for selected notes.
=> Improve note list contrast for selected notes

themes/solarized-dark/v1/theme.json
This pull request introduces a refined color palette for the list view component, resulting in improved visual clarity and consistency. Key changes include:
- Optimized Background Color: Adjusted the background color to enhance readability and reduce eye strain.
- Improved Highlight Color: The color of highlighted text has been modified to ensure better visibility when text is selected.
=> Updated colors in List View and Highlights

themes/solarized-light/v1/theme.json
- Optimized Background Color in List View: Adjusted the background color to enhance readability on selected notes.  
- Improved Highlight Color on Editor: The color of highlighted text has been modified to ensure better visibility when text is selected.
=> Updated colors in List View and highlighted words.

themes/mystic-dawn/v1/theme.json, themes/mystic-night/v1/theme.json, themes/nanab-berry/v1/theme.json, themes/solarized-dark/v1/theme.json, themes/solarized-light/v1/theme.json
Increased the themes version number.
Themes:
- Mystic Dawn
- Mystic Light
- Solarized Dark
- Solarized Light
- Nanab Berry
=> Updated themes version number

themes/gruvbox-light/v1/theme.json
Fix background color in the editor, before was #f2e5bc and the correct colors should be #fbf1c7
=> updated gruvbox light

themes/default-dark/v1/theme.json
* fixes https://github.com/streetwriters/notesnook/issues/6815
Closes https://github.com/streetwriters/notesnook/issues/6815
=> chore: update default dark theme

themes/kanagawa-dark/v1/theme.json
=> Changed selection colors

themes/fairy-forest-dark/v1/theme.json, themes/fairy-forest-light/v1/theme.json
Fixed some weird hover colors on Fairy Forest Light and Dark Themes
=> Fairy Forest Hover Colors

themes/cybernetic-punk/v1/code-block.css, themes/cybernetic-punk/v1/theme.json
=> add cybernetic-punk theme
